name:                minimal
version:             0.1.0.0
description:         Template for minimal Haskell stack app.
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/minimal.git

dependencies:
- array
- base >= 4.7 && < 5
- bytestring
- containers
- text

default-extensions:
- DuplicateRecordFields
- GADTs
- ImportQualifiedPost
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- RecordWildCards
- ScopedTypeVariables
# - Strict

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
# Default optimisation is -O == -O1

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        minimal
